homepage:
    resource: "@TobogunHomepageBundle/Controller/"
    type:     annotation
# app/config/routing.yml
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

sonata_basket:
    resource: @SonataBasketBundle/Resources/config/routing/basket.xml
    prefix: /shop/basket

sonata_order:
    resource: @SonataOrderBundle/Resources/config/routing/order.xml
    prefix: /shop/user/invoice

sonata_product_catalog:
    resource: @SonataProductBundle/Resources/config/routing/catalog.xml
    prefix: /shop/catalog

sonata_product:
    resource: @SonataProductBundle/Resources/config/routing/product.xml
    prefix: /shop/product

sonata_payment:
    resource: @SonataPaymentBundle/Resources/config/routing/payment.xml
    prefix: /shop/payment

sonata_invoice:
    resource: @SonataInvoiceBundle/Resources/config/routing/invoice.xml
    prefix: /shop/user/invoice