homepage:
    resource: "@TobogunHomepageBundle/Controller/"
    type:     annotation
# app/config/routing.yml
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin